%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\KSW\Desktop\Beans.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/04/25 13:37:08

%% Initialize variables.
filename = 'C:\Users\KSW\Desktop\Beans.csv';
delimiter = ',';
startRow = 2;
endRow = 15;

%% Format string for each line of text:
%   column2: double (%f)
%	column3: double (%f)
%   column4: double (%f)
%	column5: double (%f)
%   column6: double (%f)
%	column7: double (%f)
%   column8: double (%f)
%	column9: double (%f)
%   column10: double (%f)
%	column11: double (%f)
%   column12: double (%f)
%	column13: double (%f)
%   column14: double (%f)
%	column15: double (%f)
%   column16: double (%f)
%	column17: double (%f)
%   column18: double (%f)
%	column19: double (%f)
%   column20: double (%f)
%	column21: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'HeaderLines', startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
A = dataArray{:, 1};
A1 = dataArray{:, 2};
A2 = dataArray{:, 3};
A3 = dataArray{:, 4};
A4 = dataArray{:, 5};
A5 = dataArray{:, 6};
A6 = dataArray{:, 7};
A7 = dataArray{:, 8};
A8 = dataArray{:, 9};
A9 = dataArray{:, 10};
B = dataArray{:, 11};
B1 = dataArray{:, 12};
B2 = dataArray{:, 13};
B3 = dataArray{:, 14};
B4 = dataArray{:, 15};
B5 = dataArray{:, 16};
B6 = dataArray{:, 17};
B7 = dataArray{:, 18};
B8 = dataArray{:, 19};
B9 = dataArray{:, 20};


%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;